### ISSUE TITLE
Fetch: object not found

### ISSUE THREAD

**Issue by Asgoret** [go-git/go-git#129]
Hi to all. 
I have a similar issue -> https://github.com/src-d/go-git/issues/802
I tried to play with depth in clone and fetch, but it didn't help.
Code:
```
	repo, err := git.Clone(memory.NewStorage(), nil, &git.CloneOptions{
		Auth: &http.BasicAuth{
			Username: "<username>",
			Password: "<password>,
		},
		ReferenceName: plumbing.ReferenceName(fmt.Sprintf("refs/heads/%s", branch)),
		URL:           repoURL,
		SingleBranch:  true,
		Depth:         2,
	})
.....
fmt.Println("Before infinite loop")
	for {
		fmt.Println("Inside infinite loop")
		err = repo.Fetch(&git.FetchOptions{
			Auth: &http.BasicAuth{
		 		Username: "<username>",
		 		Password: "<password>",
		 	},
		})
		if err != nil {
			log.Error(err)
		}
		cIter, err = repo.Log(&git.LogOptions{From: ref.Hash(), FileName: &neededFile})
		_ = cIter.ForEach(func(c *object.Commit) error {
			if cmt.Hash == c.Hash {
				fmt.Println("Commits equal")
			} else if cmt.Hash != c.Hash {
				fmt.Println("Do something")
			}
			return fmt.Errorf("found")
		})

	}
```
P.S. I need this infinite loop for watching is there any changes in GH.

cc @mcuadros @barnettZQG @ajnavarro

**Comment by AriehSchneier** [comment]
@pjbgf This is probably fixed by #778

**Comment by pjbgf** [comment]
@AriehSchneier thanks for the heads up. I will close this one as it seems related to the shallow clone issue, as you pointed out.
I know that `object not found` it is still happening intermittently in different scenarios, but that is being captured on other opened issues.
